[server]
headless = true
address = "0.0.0.0"
port = 8501


[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = true  # Důležité pro bezpečnost

[browser]
serverAddress = "localhost"